How much variance does the entropy regularizer have?

In [1]:
import numpy as np
import torch
from tqdm.notebook import tqdm
import math

In [2]:
N = 10
runs = 10
eps = 1e-4
param = torch.nn.Parameter(torch.tensor([0.0] * N,dtype=torch.float))
variance = 3
problem = torch.tensor([1.,2.,3.,0,0,0,0,0,0,0], dtype=torch.float)
problem = problem / problem.sum()
lr = 0.01
entropic = 0.3
def forever():
    while True:
        yield None

In [3]:
for i in tqdm(range(runs)):
    init = torch.tensor(np.random.random((N,)) * math.sqrt(12 * variance),dtype=torch.float)
    print(init)
    param.data = init
    loss = grad = math.inf
    bar = tqdm(enumerate(forever()))
    for i, _ in bar:
        if grad < eps or i > 100000:
            break
        loss = ((param.log_softmax(-1).exp() - problem) ** 2).sum() + (-entropic * (param.log_softmax(-1) * param.softmax(-1)).sum())
        loss.backward()
        param.data -= lr * param.grad
        grad = param.grad.norm()
        param.grad = None
        bar.desc = f"g={grad.item():>.4f} l={loss.item():>.4f} {param.log_softmax(-1).exp()}"


tensor([5.8729, 4.0028, 0.7207, 5.8576, 5.4465, 0.3452, 1.9188, 4.7169, 0.3531,
        4.5309])



tensor([3.9043, 2.8377, 5.7540, 2.8823, 5.9682, 3.6181, 2.9625, 4.5385, 4.4706,
        1.1990])



tensor([2.5010, 0.5972, 1.9245, 4.5400, 2.2972, 1.3562, 0.1854, 4.0659, 3.4091,
        1.0534])



tensor([2.8299, 3.8988, 5.1230, 1.6427, 5.2338, 4.4068, 5.2003, 0.5399, 0.7090,
        1.5709])



tensor([2.0876, 2.6877, 5.1922, 4.0891, 3.8151, 1.0459, 3.1647, 1.2700, 3.4483,
        2.4628])



tensor([2.8415, 3.9781, 0.7341, 5.7719, 5.1381, 1.5939, 0.2874, 0.4330, 0.3033,
        4.5097])



tensor([5.9933, 1.3118, 3.6527, 3.2802, 2.9033, 3.5107, 0.5244, 0.6269, 0.9763,
        3.8202])



tensor([0.8003, 0.9004, 3.7816, 2.0768, 5.5464, 4.5662, 1.0318, 3.7464, 3.3578,
        3.3983])



tensor([3.1816, 4.2381, 3.9585, 5.3931, 5.7587, 2.9993, 2.7757, 5.3566, 1.8076,
        3.1623])



tensor([2.4634, 3.9788, 0.1450, 2.4581, 1.3343, 0.5912, 4.2822, 1.0977, 3.7099,
        3.9010])
